[intercom]
; Route calls to Extension 100 (Mobile Phone)
exten => 100,1,Dial(SIP/100)
exten => 100,n,Hangup()

; Route calls to Extension 101 (Mobile Phone 2)
exten => 101,1,Dial(SIP/101)
exten => 101,n,Hangup()

; Route calls to Extension 102 (PC Desktop)
exten => 102,1,Dial(SIP/102)
exten => 102,n,Hangup()

; Route calls to Extension 200 (ESP32)
exten => 200,1,Dial(SIP/200)
exten => 200,n,Hangup()
